import logo from '../assets/Company.jpg'

export const offresList = [
    {
        id : 1,
        photo : logo,
        nom : 'CompanyOne',
        category : 'vitre',
        wilaya : 'Bejaia',
        prix : 666,
        description : 'une description des plus pertinente pour notre societe, tout cela de le but de tester le désigne',
    },
    {
        id : 2,
        photo : logo,
        nom : 'CompanyTwo',
        category : 'vitre',
        wilaya : 'Alger',
        prix : 666,
        description : 'une description des plus pertinente pour notre societe, tout cela de le but de tester le désigne',
    },
    {
        id : 3,
        photo : logo,
        nom : 'CompanyThree',
        category : 'domicile',
        wilaya : 'Batna',
        prix : 666,
        description : 'une description',
    },
    {
        id : 4,
        photo : logo,
        nom : 'CompanyThree',
        category : 'domicile',
        wilaya : 'Batna',
        prix : 666,
        description : 'une description',
    },
    {
        id : 5,
        photo : logo,
        nom : 'CompanyThree',
        category : 'entreprise',
        wilaya : 'Batna',
        prix : 666,
        description : 'une description',
    },
    {
        id : 6,
        photo : logo,
        nom : 'CompanyThree',
        category : 'domicile',
        wilaya : 'Batna',
        prix : 666,
        description : 'une description',
    },
    {
        id : 7,
        photo : logo,
        nom : 'CompanyTwo',
        category : 'vitre',
        wilaya : 'Alger',
        prix : 666,
        description : 'une description des plus pertinente pour notre societe, tout cela de le but de tester le désigne',
    },
    {
        id : 8,
        photo : logo,
        nom : 'CompanyTwo',
        category : 'vitre',
        wilaya : 'Alger',
        prix : 666,
        description : 'une description des plus pertinente pour notre societe, tout cela de le but de tester le désigne',
    },
    {
        id : 9,
        photo : logo,
        nom : 'CompanyTwo',
        category : 'vitre',
        wilaya : 'Alger',
        prix : 666,
        description : 'une description des plus pertinente pour notre societe, tout cela de le but de tester le désigne',
    }
]